MugedaHelper={};function G(a){return document.getElementById(a)}function E(a,c,b){c||(c="load");b||(b=window);b.attachEvent?b.attachEvent("on"+c,a):b.addEventListener(c,a,false)}function json(a){try{return eval("("+a+")")}catch(c){return null}}function _ED(a){if(!a||typeof a=="string")return a;var c="",b;for(b in a)c+="&"+b+"="+encodeURIComponent(a[b]);c&&(c=c.substr(1));return c}
function ajax(a){var c=/POST/i.test(a.type),b=a.data||"",d=a.dataType,e=a.url||location.href,f=/\?/.test(e)?"&":"?",g=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP");g.onreadystatechange=function(b){if(g.readyState==4)g.status==200?(b=g.responseText,d=="json"&&(b=json(b)),(c=a.success)&&c(b)):a.error&&a.error(g.status,g)};if(typeof b=="object"){var k=[],i;for(i in b)k.push(encodeURIComponent(i)+"="+encodeURIComponent(b[i]));b=k.join("&")}g.open(c?
"POST":"GET",e+(c?"":(b?f:"")+b+(a.cache?"":(!b&&f=="?"?"?":"&")+"_="+(new Date).getTime())),a.async===false?false:true);c&&g.setRequestHeader("Content-Type","application/x-www--urlencoded");g.send(b);return g}
function isMobile(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?true:false}function fo(a){var c=0,b=0;do c+=a.offsetLeft||0,b+=a.offsetTop||0;while(a=a.offsetParent);return{x:c,y:b}}function fe(a){a=a||event;return{x:a.pageX||a.x,y:a.pageY||a.y}}
function fc(a){a&&a.stopPropagation?a.stopPropagation():event.cancelBubble=true}function getClass(a,c){for(var b=RegExp("(^|\\s*)"+a+"(\\s*|$)"),d=c?document.getElementsByTagName(c):document.getElementsByTagName("*")||document.all,e=[],f=0,g=d.length;f<g;f++)b.test(d[f].className)&&e.push(d[f]);return e}JSON.clone=function(a){return JSON.parse(JSON.stringify(a))};
function getElementOffset(a){for(var c=0,b=0;a&&a.tagName!="BODY";)c+=a.offsetTop,b+=a.offsetLeft,a=a.offsetParent;return{top:c,left:b}}
MugedaMraid={mraidReadyStatus:0,mraidState:void 0,getStage:function(){var a=null;for(window.event&&(a=window.event.target||window.event.srcElement);a;){if(a.id.indexOf("_stage")>0||a.getAttribute("data-mid")==0)break;a=a.parentNode}return a?a:document.getElementsByClassName("MugedaStage")[0]},setMraidState:function(a){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=_mrmcp.display_mode,b=mraid.getPlacementType();this.mraidState=a.toLowerCase();var d=document.getElementById("mugeda_close_button");
switch(this.mraidState){case "default":if(c!="expand"&&b!="interstitial"&&d)d.style.display="none";typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(1);break;case "expanded":(c=="auto"||c=="expand"||c=="interstitial")&&setTimeout(function(){d.style.display="block"},50);break;case "resized":setTimeout(function(){d.style.display="block"},50)}},openLink:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;_mrmcp.destination_url&&_mrmcp.destination_url.indexOf("%DESTURL%")<0&&(a=
_mrmcp.destination_url);var b="ts="+(new Date).getTime();b+="&_moid="+(_mrmcp.owner_id||"");b+="&_mcid="+(_mrmcp.creative_id||"");b+="&_mw="+(_mrmcp.width||"");b+="&_mh="+(_mrmcp.height||"");b+="&_mtp="+(_mrmcp.type||"");b+="&_mtt="+escape(_mrmcp.title||"");var d=_mrmcp.custom_params;d&&d.indexOf("%CUSTOMPARAM%")<0&&(b+="&"+d);if((d=_mrmcp.redirect_url)&&d.indexOf("%LINK%")<0)var e=a.indexOf("?"),e=e<0?"?":"&",a=d+(d.lastIndexOf("=")==d.length-1?escape(a+e+b):"");var e=a.indexOf("?"),d=e<0?"?":"&",
e=e==a.length-1,f=window.location.search;if(f){for(var f=f.split("?")[1],g=f.split("&"),k=g.length,i=0;i<k;i++){var h=g[i].split("=");if(h.length==2){var t=h[1];h[0].toLowerCase()=="mugeda_click_link"&&(a=unescape(t),e=a.indexOf("?"),d=a<0?"?":"&",e=e==a.length-1)}}a+=(e?"":d)+f;e=false;f.length&&(d="&")}a+=(e?"":d)+b;this.mraidReadyStatus==1?c=="internal"?mraid.open(a):c=="expand"?this.expand(a,0):window.open(a):c=="internal"?window.location=a:c=="expand"?this.expand(a):window.open(a);MugedaTracker.fireEvent({category:"link",
action:c,label:a,value:0})},expand:function(a,c,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(this.mraidReadyStatus!=1){if(a&&a.length){var d=document.URL.match(/client.*preview.*id/),e=b=null;try{b=(d?window:window.parent).document,e=b.getElementById("mugeda_expanded")||b.createElement("div")}catch(f){window.open(a);return}a.match(/^(\/|http:|https:)/i)||(a=(_mrmcp.creative_path||"")+a);e.id="mugeda_expanded";e.style.display="block";e.style.position="fixed";e.style.width=(b.defaultView.innerWidth||
b.documentElement.clientWidth)+"px";e.style.height=(b.defaultView.innerHeight||b.defaultView.innerHeight)+"px";e.style.left="0px";e.style.margin="0";e.style.padding="0";e.style.border="none";e.style.top="0px";e.style.background="#000";e.innerHTML="<iframe id='mugeda_expand_iframe' src='"+a+"' style='border:none;width:100%;height:100%;margin:0px;padding:0px;'></iframe>";b.body.appendChild(e);MugedaBehavior.processCloseButton("expand",b)}}else{var b=b||{},e=mraid.getMaxSize(),d=parseInt(b.width)||e.width,
e=parseInt(b.height)||e.height,a=a||b.url,g=!a||a.length==0;c==1?(a=parseInt(b.left)||0,b=parseInt(b.top)||0,MugedaBehavior.processCloseButton("resize"),mraid.setResizeProperties({width:d,height:e,offsetX:a,offsetY:b,allowOffscreen:false}),mraid.resize()):(mraid.setExpandProperties({width:d,height:e,isModal:true,useCustomClose:_mrmcp.display_mode?true:false}),g?(mraid.expand(),MugedaBehavior.processCloseButton()):mraid.expand(a))}},sendEmail:function(a){window.open("mailto:"+a.email_addr+"?subject="+
a.email_title+"&body="+a.email_body,"_self")},savePicture:function(a){this.mraidReadyStatus==1&&mraid.supports("storePicture")&&mraid.storePicture(a.url)},addCalendarEvent:function(a){this.mraidReadyStatus==1&&mraid.supports("calendar")&&mraid.createCalendarEvent({summary:a.calendar_summary,description:a.calendar_desc,location:a.calendar_location,start:a.calendar_start_time,end:a.calendar_end_time})},createHTML5VideoTag:function(){var a=G("mugedaVideoHolder");if(a)return a;a=document.createElement("div");
a.id="mugedaVideoHolder";a.style.margin=0;a.style.padding=0;a.style.backgroundColor="rgba(0,0,0,0.8)";a.style.position="absolute";a.style.top=0;a.style.left=0;a.style.width=0;a.style.height=0;a.style.zIndex=1;_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=(_mrmcp.creative_path||"")+"close_button.png",c='<video id="mugeda_video" style="width:100%;height:100%;position:absolute;z-index:2;"></video>'+('<div id="mugeda_video_close" align="middle" style="position: absolute;color:white;width:36px;height:36px;right:0px;top: '+
(navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)?0:0)+"px;cursor:pointer;background-image: url("+c+');z-index:3;"></div>');a.innerHTML=c;a.style.display="none";document.body.appendChild(a);G("mugeda_video").onclick=function(){this.paused?this.play():this.pause()};return a},loadUrl:function(a){var c=a.id||(new Date).getTime(),b=a.url||"",d=a.left||0,e=a.top||0,f=isNaN(a.width)?window.aniData?window.aniData.width:320:Math.max(0,a.width),g=isNaN(a.height)?window.aniData?window.aniData.height:
240:Math.max(0,a.height),k=a.before||null,i=a.style,h=a.scroll,t=a.parent,v=a.onload,j=a.onclose,o=a.position,r=a.close_position;if(!k&&!t){var q=typeof Mugeda!="undefined"&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&q&&(q=getElementOffset(q),d+=q.left,e+=q.top)}var n=G(c);n||(n=document.createElement("div"),t?t.appendChild(n):k?k.parentNode.insertBefore(n,k):document.body.appendChild(n));n.id=c;n.style.margin=0;n.style.padding=0;n.style.backgroundColor="transparent";
n.style.position=o?o:"fixed";n.style.top=0;n.style.left=0;n.style.width=0;n.style.height=0;switch(r){case "leftTop":r="left:4px;top:4px;";break;case "leftbottom":r="left:4px;bottom:4px;";break;case "rightbottom":r="right:4px;bottom:4px;";break;default:r="right: 4px;top: 4px;"}n.innerHTML="<iframe "+(h?"":"scrolling=no ")+'id="'+c+'_iframe" style="border:none; width:100%;height:100%; '+(h?"":"overflow:hidden;")+' " ></iframe>'+('<div id="'+c+'_iframe_close" align="middle" style="position: absolute;color:white;width: 24px;height: 24px; '+
r+'cursor:pointer;background: rgba(0,0,0,0.5);border: 3px solid white;border-radius: 15px;font-family:arial;font-size: 16px;line-height:24px;">&#10006;</div>');n.style.display="none";n.style.top=e+"px";n.style.left=d+"px";n.style.width=f+"px";n.style.height=g+"px";n.style.display="block";n.style.cssText+=i;G(c+"_iframe_close").style.display=a.close_button?"block":"none";setTimeout(function(){if(a.close_button)G(c+"_iframe_close").onclick=function(){n.style.display="none";G(c+"_iframe").src="about:blank";
j&&j(n)}},100);setTimeout(function(){var a=G(c+"_iframe");a.src=b;if(v)try{a.onload=function(){v(a);a.onload=null}}catch(d){}},100);return n},playAudio:function(a,c){var b=false;if(!a||!a.audio_url||!a.audio_url.length)return false;var d=typeof Mugeda!="undefined"&&Mugeda.getAudioCache?Mugeda.getAudioCache(a.audio_url,a.audioId):MugedaBehavior.localCache[a.audio_url];if(d){if(d.loop=parseInt(a.audio_loop)==1?true:false,d.play)if(d.webAudio)b=d.play(a.event=="click"||c?true:false);else if(a.event==
"click"){try{d.pause(),d.currentTime=0}catch(e){}setTimeout(function(){d.play()},5)}else(d._68!=1||c)&&setTimeout(function(){d.play();d._68=1;b=true},10)}else{var d=new Audio,f=document.createElement("source"),g=a.audio_url.lastIndexOf("."),g=a.audio_url.substring(g+1),k=true;switch(g){case "ogg":f.type="audio/ogg";break;case "mp3":f.type="audio/mpeg";break;default:k=false,console.log("Audio extension ("+g+") not supported.")}if(k){f.src=a.audio_url;d.appendChild(f);d.autoplay=false;d.preload="auto";
d.load();var i=document.getElementById("mugeda_resource_loading");if(!i)i=document.createElement("img"),i.id="mugeda_resource_loading",i.style.position="fixed",i.style.right="2px",i.style.top="2px",i.style.display="block",i.src=(_mrmcp.creative_path||"")+"loading.gif",document.body.appendChild(i);i.style.display="block";b=true;d.addEventListener("canplay",function(){i.style.display="none";d.play()},false);MugedaBehavior.localCache[a.audio_url]=d}}return b},playHTML5Video:function(a){var c=a.left||
0,b=a.top||0,d=isNaN(a.width)?"100%":Math.max(0,a.width)+"px",e=isNaN(a.height)?"100%":Math.max(0,a.height)+"px",f=window.Mugeda&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&f&&!a.video_holder&&!isNaN(a.left)&&(f=getElementOffset(f),c+=f.left,b+=f.top);f=this.createHTML5VideoTag();f=G("mugedaVideoHolder");if(a.video_holder){var g=null,k=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null;if(k&&k.scene){var g=a.video_holder,g=g.split("/"),i=a.video_object===1;g.length===
2?(k=k.scene.getObjectByName(i?g[1]:g[0]),i?(g=k?k.scene.objectHash[g[0]]:null,a.url=g?g.data.param.videoUrl:a.url):g=k?k.scene.getObjectByName(g[1]):null):i?(g=k.scene.objectHash[a.video_holder],a.url=g?g.data.param.videoUrl:a.url):g=k.scene.getObjectByName(a.video_holder);g&&g.dom&&g.dom.appendChild(f)}else if(window.mugedaCss&&mugedaCss.magic&&(k=document.getElementById(mugedaCss.magic+"stage")))g=a.video_holder,g=g.split("/").map(function(a){return"."+a}),(g=k.querySelectorAll(g.join(" ")))&&
g.length&&g[0].appendChild(f)}else f.parentNode!=document.body&&document.body.appendChild(f);f.style.top=b+"px";f.style.left=c+"px";f.style.width=d;f.style.height=e;f.style.display="block";var h=G("mugeda_video"),t=G("mugeda_video_close");t.style.display=a.close_button?"block":"none";a.video_controls?h.setAttribute("controls","controls"):h.removeAttribute("controls");h.src=a.url;h.load();setTimeout(function(){h.play();setTimeout(function(){if(a.close_button){var b=isMobile()?"touchend":"click";t.addEventListener(b,
function(a){a.stopPropagation();if(a=G("mugeda_video"))a.src="",a.load();G("mugedaVideoHolder").style.display="none"},false)}},1E3)},10)},playVideo:function(a){a=a||{};if(!a.video_url)return false;this.mraidReadyStatus!=1?this.playHTML5Video({url:a.video_url,video_object:parseInt(a.video_object,10),video_holder:a.video_holder,left:parseInt(a.video_left,10),top:parseInt(a.video_top,10),width:parseInt(a.video_width,10),height:parseInt(a.video_height,10),close_button:parseInt(a.video_close,10)==1,video_controls:parseInt(a.video_controls,
10)==1,auto:parseInt(a.video_autoplay,10)==1}):mraid.playVideo(a.video_url)},stopVideo:function(){var a=G("mugeda_video");if(a)a.src="",a.load();(a=G("mugedaVideoHolder"))&&(a.style.display="none")},sendShortMessage:function(a){window.open("sms:"+a.phone_number+"?body="+a.sms_body,"_self")},makePhoneCall:function(a){window.open("tel:"+a.phone_number,"_self")}};
MugedaBehavior={localCache:{},pause:function(){typeof Mugeda!="undefined"&&Mugeda.pause&&Mugeda.pause()},resume:function(a){typeof Mugeda!="undefined"&&Mugeda.resume&&Mugeda.resume(a)},nextPage:function(){typeof Mugeda!="undefined"&&Mugeda.nextPage&&Mugeda.nextPage()},prevPage:function(){typeof Mugeda!="undefined"&&Mugeda.prevPage&&Mugeda.prevPage()},gotoPage:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoPage&&Mugeda.gotoPage(a)},disablePage:function(){typeof Mugeda!="undefined"&&Mugeda.disablePage&&
Mugeda.disablePage()},enablePage:function(){typeof Mugeda!="undefined"&&Mugeda.enablePage&&Mugeda.enablePage()},next:function(){typeof Mugeda!="undefined"&&Mugeda.next&&Mugeda.next()},previous:function(){typeof Mugeda!="undefined"&&Mugeda.previous&&Mugeda.previous()},gotoAndPlay:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(a)},gotoAndStop:function(a){gotoAndPause(a)},gotoAndPause:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPause&&Mugeda.gotoAndPause(a)},
callback:function(a,c){if(window&&c.name&&c.name.length&&window[c.name])window[c.name](a,c.key,c.value)},map:function(a){var c=a.map_key.replace(/(\n|\r)/g,"+"),b=a.map_address.replace(/(\n|\r)/g,"+"),d=navigator.userAgent.toLowerCase().indexOf("android")>-1,e=parseInt(a.map_type,10),f=function(){var a=G("mugedaVideoHolder");if(a)a.style.display="none";if(a=G("mugedaMap-mask"))g(1);else{var a=document.createElement("div"),b=window._mrmcp&&_mrmcp.creative_path?_mrmcp.creative_path+"loading.gif":"/images/loading.gif";
a.id="mugedaMap-mask";a.className="mugedaMapControl";a.innerHTML='<p id="mugedaMap-title"><a id="mugedaMap-back">\u8fd4\u56de</a>\u4f4d\u7f6e\u4fe1\u606f</p><div id="mugedaMap-con"></div><div id="mugedaMap-loading"><div class="spinner"></div><style>.mugedaMapControl {position:absolute;left:0;top:0;height:100%;width:100%;z-index:999999;}.mugedaMapMaskVisible {-webkit-transition:transform 1s;transform:translate3d(-100%, 0, 0);-webkit-transform:translate3d(-100%, 0, 0);}.mugedaMapControl #mugedaMap-title {position:fixed;height:44px;line-height:44px;width:100%;text-align:center;z-index:1;background:rgba(255,255,255,.8);margin:0;}.mugedaMapControl #mugedaMap-con {height:100%;width:100%;}.mugedaMapControl #mugedaMap-back {position:absolute;left:5px;display:inline-block;height:100%;width:40px;cursor:pointer;}.mugedaMapControl #mugedaMap-loading {position:absolute;width:100%;height:100%;line-height:100%;left:0;top:44px;display:none;background:#fff;z-index:2;}.mugedaMapControl .spinner {position:absolute;width:20px;height:30px;left:50%;top:50%;margin:-50px 0 0 -10px;background-image:url('+
b+');background-repeat:no-repeat;background-size:contain;}.mugedaMapControl .spinner:after {content: "\u52a0\u8f7d\u4e2d ...";position:absolute;width:80px;left:-25px;top:120%;}</style>';document.body.appendChild(a);(a=G("mugedaMap-back"))&&a.addEventListener("click",function(a){a.stopPropagation();g(0)},false)}},g=function(a){var b=G("mugedaMap-mask");b&&b.classList.toggle("mugedaMapMaskVisible",!a)},k=function(a){var b=G("mugedaMap-loading");if(b)b.style.display=a?"block":"none"},i,h,t=function(a,
b,c,d){i||(i=new BMap.Map("mugedaMap-con"));i.centerAndZoom(c||"\u5317\u4eac",11);i.addControl(new BMap.ZoomControl);h||(h=new BMap.LocalSearch(i,{renderOptions:{map:i,autoViewport:true},onSearchComplete:function(a){typeof d==="function"&&d.call(i,a)}}));b&&a?h.searchNearby(b,a):h.search(b)},v=function(a,b,c){if(e===0){var d=["http://api.map.baidu.com/getscript?type=quick&file=api&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0","http://api.map.baidu.com/getscript?type=quick&file=feature&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0"],
b=decodeURIComponent(b),a=decodeURIComponent(a);f();k(1);for(var i=0,c=0,h=d.length;c<h;c++){var g=document.createElement("script");g.src=d[c];g.onload=function(){++i===h&&t(a,b,"",function(a){a.getNumPois()===0&&alert("\u62b1\u6b49\uff0c\u6ca1\u6709\u641c\u7d22\u5230\u76f8\u5173\u4fe1\u606f");k(0)})};document.head.appendChild(g)}}else if(d="https://maps.google.com/maps?q="+(a+""+(b.length?"+near+"+b:""))+"&z=12",g=parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||
[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||false,c==1){if(c=document.getElementById("aMugedaGeoLocation"))c.href=d,d=document.createEvent("HTMLEvents"),d.initEvent("click",true,true),c.dispatchEvent(d)}else g&&g<6?window.location.href=d:window.open(d,"_blank")};if(!d&&b.length==0&&navigator.geolocation){a=document.getElementById("aMugedaGeoLocation");if(!a)a=document.createElement("a"),a.id="aMugedaGeoLocation",a.style.display="none",a.href="",a.target="_blank",document.body.appendChild(a);
navigator.geolocation.getCurrentPosition(function(a){b=a.coords.latitude+","+a.coords.longitude;v(c,b,1)})}else v(c,b)},popupForm:function(a,c){function b(a,b){if(a&&b)return a.querySelector("#"+b)}function d(a){if(window.localStorage&&window.localStorage.getItem)return unescape(localStorage.getItem(a)||"");var b,c,d,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(c=e[b].substr(0,e[b].indexOf("=")),d=e[b].substr(e[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a.toLowerCase())return unescape(d);
return""}function e(a,b){if(window.localStorage&&window.localStorage.getItem)try{localStorage.setItem(a,escape(b))}catch(c){console.info("Oops, localStorage full"),localStorage.clear(),localStorage.setItem(a,escape(b))}else{var d=new Date;d.setDate(d.getDate()+3);d=escape(b)+"; expires="+d.toUTCString();document.cookie=a.toLowerCase()+"="+d}}function f(a){var b=document.querySelector(".MugedaStage")?null:G("viewbox")||G("frame");if(b)b.style.display=a?"":"none";return b?true:false}function g(a){if(c){var b=
function(a,b){Array.prototype.forEach.call(a,function(a,c){b(a,c)})};b(a.querySelectorAll(".popupFormInputBox input,.popupFormInputBox textarea"),function(a){a.value=""});b(a.querySelectorAll(".popupFormRadioList input,.popupFormCheckbox input"),function(a){a.checked=false});b(a.querySelectorAll(".popupFormSelectList select"),function(a){a.value=a.querySelector("option").getAttribute("value")})}else if(b=a.querySelector("form"),b.style.bottom=-b.offsetHeight+"px",a.style.background="rgba(0,0,0,0)",
setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},500),f(1)&&(document.body.style.overflowY="hidden",isMobile()))document.body.style.height="100%"}var k=a.openTarget=="default"||a.openTarget=="frame"||a.openTarget=="page";if(a&&!(a.openTarget=="callback"&&!a.callback||a.openTarget!="callback"&&a.openTarget!="customizable"&&!k&&!a.url)){var k=document.documentElement.clientWidth,i=document.documentElement.clientHeight,h=[],t=function(b,c){var c=c||{},d=c.detail,e=c.form||(d?d.form:null),
d={item:d,form:e,title:a.title,hideItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="none")},showItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="block")}},c=document.createEvent("Events");c.initEvent(b,true,true);c.detail=d;window.dispatchEvent(c)};window.addEventListener("_mugedaFormChanged",function(a){t("mugedaFormChanged",a)});var v=a.items||[];window.popupFormFields=v;if(!a.html){var j="";c?(j+='<div class="popupFormContent">',a.title&&(j+=
'<div align="center" class="popupFormTitle"><h2>'+a.title+"</h2></div>")):(j+='<div align="center" class="popupFormTitle">',j+='<div class="title-col-2" align="center"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel"></div>',j+='<div class="title-col-6" align="center"><h2>'+(a.title||"&nbsp;")+"</h2></div>",j+='<div class="title-col-2" align="center"><input id="actionButton" type="submit" value="'+a.submitName+'" class="popupFormSubmit"></div>',j+="</div>",
j+='<div class="popupFormContent">');var o=navigator.userAgent.toLowerCase(),r=o.indexOf("android")>-1,q=parseFloat(o.slice(o.indexOf("android")+8)),n="",y=0,z={phone:"tel",input:"text"};r&&q<3&&(n="-webkit-transform: scale(2,2);-webkit-transform-origin:center center;");for(var F=c?"":":",o=0;o<v.length;o++){var l=v[o],x=(l.value||"").trim();if(x){for(var x=x.split("\n"),p=[],u=0;u<x.length;u++){var H=x[u].split("("),A=H[0],H=(H[1]||"").replace(/\)$/,"")||A,C=["FORMID",H,o,u].join("_");p[u]={id:C,
text:A,value:H}}x=p}C='id="popupFormField_'+o+'"';switch(l.type){case "radio":j+="<div "+C+' class="popupFormRadioList">';l.description&&(j+='<label class="inputlabel">'+l.description+(l.required?"*":"")+F+"</label>");j+='<div class="mformradio">';for(u=0;u<x.length;u++)p=x[u],A=d(p.id),j+='<label><input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="radio" name="'+l.id+'" value="'+
p.value+'" id="'+p.id+'" '+(A=="true"?"checked=checked":"")+" ><span "+(u==x.length-1?"":" style='border-right:1px solid "+a.background+"'")+">"+p.text+"</span></label>",h[p.id]=p.id;j+="</div></div>";break;case "checkbox":j+="<div "+C+' class="popupFormCheckbox">';l.description&&(j+='<label class="inputlabel">'+l.description+(l.required?"*":"")+F+"</label>");j+='<div class="mformcheck">';j+=l.rangeType==="vertical"?"<table>":"";for(u=0;u<x.length;u++)p=x[u],A=d(p.id),j+=l.rangeType==="vertical"?
'<tr><td><input type="checkbox" value="'+p.value+'" id="'+p.id+'" '+(A=="true"?"checked=true":"")+' ></td><td><label for="'+p.id+'" >'+p.text+"</label></td></tr>":'<input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="checkbox" name="'+l.id+'" value="'+p.value+'" id="'+p.id+'" '+(A=="true"?"checked=true":"")+' ><label for="'+p.id+'" >'+p.text+"</label>",h[p.id]=p.id;r&&q<3&&l.rangeType!=
"vertical"&&(y=6);j+=l.rangeType==="vertical"?"</table>":"";j+="</div></div>";break;case "select":j+="<div "+C+' class="popupFormSelectList">';l.description&&(j+='<label class="inputlabel text">'+l.description+(l.required?"*":"")+F+"</label>");j+='<select class="text" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" name="'+l.id+'" id="'+("_map_"+l.description)+'">';j+='<option value="">'+l.description+
"</option>";A=d(l.description);for(u=0;u<x.length;u++)p=x[u],j+='<option value="'+p.value+'" '+(A==p.value?"selected=selected":"")+">"+p.text+"</option>";j+="</select>";j+="</div>";h[l.description]="_map_"+l.description;break;case "textarea":j+="<div "+C+' class="popupFormInputBox">';j+='<label class="inputlabel inputlabel_area">'+l.description+(l.required?"*":"")+F+'</label><textarea name="'+l.id+'" id="_mcp_'+escape(l.description)+'" rows="4" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" style="resize:none; height:48px;">'+
(l.value.length?l.value:d(l.description))+"</textarea>";j+="</div>";h[l.description]="_mcp_"+escape(l.description);break;default:j+="<div "+C+' class="popupFormInputBox">',j+='<label class="inputlabel text">'+l.description+(l.required?"*":"")+F+'</label><input class="text" name="'+l.id+'" id="_mcp_'+escape(l.description)+'" type="'+(z[l.type]||l.type)+"\" onchange=\"var event = document.createEvent('Events');event.initEvent('_mugedaFormChanged', true, true);event.detail = this;window.dispatchEvent(event);\" value=\""+
(d(l.description)||l.value)+'" '+(c?'placeholder="'+l.description+'"':"")+">",j+="</div>",h[l.description]="_mcp_"+escape(l.description)}}c&&(j+='<div class="popupFormBtn"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel">',j+='<input id="actionButton" type="submit" value="'+a.submitName+'" class="popupFormSubmit"></div>');j+="</div>";a.html=j}delete this.popupFormDiv;var m=this.popupFormDiv;if(!m){o=function(b){var b=b||".popupForm",d=1;if(/^rgba\(\d+,\s\d+,\s\d+,\s([0-9.]+)\)$/.exec(a.background))d=
RegExp.$1;d="<style>"+b+" {width:100%;font-size:"+a.fontSize+'px;font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+' * {font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+" form{position:absolute;width:100%;background-color:"+a.background+";}"+b+" *{margin:0;box-sizing:border-box;-webkit-appearance: none; -moz-appearance: none; appearance: value;}"+b+" .inputlabel{width:33%;height:28px;font-size:"+a.fontSize+"px;line-height:28px;display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:top;color:#000;}"+
b+" span{color:#333;}"+b+" label{color:#000;}"+b+" #popupFormField_0{padding-top:16px;}"+b+" .popupFormMask {position:absolute;left:0;top:0;width:100%;height:100%;background-color: "+a.background+"}"+b+" .popupFormContent {position:relative;padding-bottom:16px; background-color:rgba(255,255,255,"+d+")}"+b+" .popupFormTitle {width:100%;padding:20px 0;overflow:hidden;background-color: "+a.background+"}"+b+" h2 {font-weight:normal;font-size:"+(2+parseInt(a.fontSize))+"px;color:"+a.color+";}"+b+" h3{text-align:left;font-size:"+
a.fontSize+"px; font-weight: normal;color:"+a.color+";}"+b+" .popupFormInputBox{padding:8px 16px;text-align:left;}"+b+" .popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select{width:67%;height:28px;border:1px solid "+a.background+";font-size:"+a.fontSize+"px;padding:0;padding-left:8px;vertical-align:top;border-radius:2px;}"+b+" .popupFormSelectList{padding:8px 16px 0;}"+b+" .popupFormRadioList{padding:8px 16px 0;}"+b+" .popupFormCheckbox{padding:8px 16px 0;}"+b+" .popupFormTitle input{border-width:0;cursor:pointer;font-size:"+
a.fontSize+"px;color:"+a.color+"}"+b+" .popupFormSubmit{border:none;background:none}"+b+" .popupFormCancel{background:none;border:none;}"+b+" .popupFormRadioList input{margin:0 5px 0 8px;}"+b+" .popupFormRadioList label{vertical-align:top;}"+b+" .mformradio {background-color:#EFEFEF;border:1px solid "+a.background+";overflow:hidden;display:inline-block;}"+b+" .mformradio label{float:left; min-width:48px;}"+b+" .mformradio label span{text-align:center;padding:6px 8px;display:block;}"+b+" .mformradio label input{position:absolute;top:-99999px;}"+
b+" .mformradio input:checked + span{background-color:"+a.background+";color:#F7F7F7;}"+b+" .mformcheck{margin:0 0 8px;display:inline-block;}"+b+" .mformcheck input{"+n+"width:24px;height:24px;background-color:#EFEFEF;border:1px solid "+a.background+";vertical-align:middle;margin:3px 2px;}"+b+" .mformcheck input:checked{background-color:"+a.background+";}"+b+" .popupFormTitle .title-col-2 {float:left;width:20%;padding:0 ;text-align:center;}"+b+" .popupFormTitle .title-col-6 {float:left;width:60%;padding:0 ;}"+
b+" .popupFormTitle .title-col-2 input {font-size:"+(2+parseInt(a.fontSize))+"px;}"+b+" .mformcheck label{vertical-align:"+y+"px;font-size:"+a.fontSize+"px;padding-top:0;padding-left:4px;padding-right:8px;}";c&&(d+=b+" .popupFormBtn {width:100%;padding:20px 0 0 0;text-align:center;}",d+=b+" .popupFormSubmit {width:90px;height:30px;color:"+a.color+";background-color:"+a.background+"}",d+=b+" .popupFormCancel {width:90px;height:30px;margin-right:15px;color:"+a.color+";display:none;background-color:"+
a.background+"}");d+="</style>";return d};if(!m){var I=a.openTarget=="backend"?"popupFormIframe":"_"+a.openTarget,m=document.createElement("div");m.style.display="none";m.className=c?"popupForm2":"popupForm";j="";if(c)var B=function(b){for(var c={l:48,r:200},d=0,e=0,i=b.length;e<i;e++){for(var f=b[e],g=f.description.length,h=0,m=0;m<g;m++)h+=f.description[m].match(/[\u3400-\u9FBF]/)?2:1;d=Math.max(d,h)}d=d>8?8:d;b=a.fontSize*(d-4);d>4&&d<=8&&(c.l+=b,c.r-=b);return c}(v),j=o(".popupForm2");else j=
o();m.innerHTML='<form method="'+a.method+'" target="'+I+'" autocomplete="on"></form><iframe name="popupFormIframe" id="popupFormIframe" style="display:none"></iframe>'+j;!c&&!a.isCss?document.body.appendChild(m):(a.hwObj=B,a.iframeDiv=m,a.parentDom&&a.parentDom.appendChild(a.iframeDiv));this.popupFormDiv=m;m.form=m.childNodes[0];m.form.onclick=function(){};self=this;c||m.addEventListener(isMobile()?"touchend":"mouseup",function(a){if(!window.cardFrame){if(a.target==m)g(m),self.popupFormDiv=null,
a.stopPropagation();var b=a.target.nodeName.toLowerCase(),c=(a.target.type||"").toLowerCase();["input","textarea","select"].indexOf(b)>=0&&c!="checkbox"&&c!="submit"&&(a.target.focus(),r&&setTimeout(function(){a.target.scrollIntoView();a.target.scrollIntoViewIfNeeded&&a.target.scrollIntoViewIfNeeded()},500),a.stopPropagation());c=="button"&&a.stopPropagation()}});m.form.onsubmit=function(){function d(){var e=[],i=v;if(!c)i=window.popupFormFields;for(var f=0;f<i.length;f++){var h=i[f],j=b(m,"popupFormField_"+
f),l="",k=j.querySelectorAll("select");k.length==0&&(k=j.querySelectorAll("textarea"),k.length==0&&(k=j.querySelectorAll("input")));if(k.length==1)l=k[0].value||"";else if(k.length>1){for(var l=[],z=0;z<k.length;z++)if(j=k[z],j.checked&&(l.push(j.value),j.type=="radio"))break;l=l.join(",")}if(h.required&&!l){alert((h.description||"item")+" required");k[0].focus();return}if(l)switch(h.type){case "phone":if(!/^\d+$/.test(l)){alert((h.description||"Phone number")+" required");k[0].focus();return}break;
case "email":if(!/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(l)){alert((h.description||"Email")+" required");k[0].focus();return}}a.openTarget==="default"?e.push(encodeURIComponent(h.description+"("+h.id+")")+"="+encodeURIComponent(l||"")):e.push(encodeURIComponent(h.id)+"="+encodeURIComponent(l||""))}if("popupFormIframe"==I)G("actionButton").value=a.pendingName;e=e.join("&");i=a.url+"?"+e;a.loadFinished=function(){g(m);self.popupFormDiv=null};if(a.openTarget=="customizable")i={callback:function(){a.msg&&
alert(a.msg)},cancel:false},window.MugedaCard&&MugedaCard.finalizeCustomParameters&&MugedaCard.finalizeCustomParameters(e,i),i.cancel!==true&&i.callback(),a.loadFinished();else if(a.openTarget=="default"||a.openTarget=="page"||a.openTarget=="frame"||a.openTarget=="callback"){f="";i=0;window._mrmcp&&(f=window._mrmcp.creative_id||"");if(f==""&&/\/edit\/(\w+)\&?/.test(top.location.href))f=RegExp.$1,i=f.length<16?1:2;else if(/id=(\w+)\&?/.test(window.location.search))i=3,f=RegExp.$1;h=function(a,b,c){var c=
c||"post",d=document.createElement("form"),e=document.createElement("iframe");d.setAttribute("method",c);d.setAttribute("action",a);a="__iframe"+Math.random()*1E4;e.setAttribute("id",a);e.setAttribute("name",a);d.setAttribute("target",a);e.style.width=0;e.style.height=0;e.style.display="none";e.addEventListener("load",function(){});a=0;for(c=b.length;a<c;a++){var i=b[a].split("="),f=i[0],i=i[1],h=document.createElement("input");h.setAttribute("type","hidden");h.setAttribute("name",f);h.setAttribute("value",
i);d.appendChild(h)}document.body.appendChild(d);document.body.appendChild(e);d.submit()};f&&/^[a-z\-]+\.mugeda\.com$/.test(window.location.hostname)&&h("http://weika.mugeda.com/server/cards.php/saveform",(e+"&crid="+f+"&mode="+i).split("&"));a.openTarget=="callback"?a.callback&&window[a.callback]?(i={callback:function(){a.msg&&alert(a.msg)},cancel:false},window[a.callback](e,i),MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0}),i.cancel!==true&&
i.callback()):console.log("No callback function found. Skipping..."):a.openTarget=="frame"?a.callback&&a.callback():a.openTarget=="page"&&a.callback&&a.callback();a.loadFinished()}else try{window.open(i,I),G("popupFormIframe").onload=function(){a.loadFinished();MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0});a.msg&&alert(a.msg)}}catch(F){a.loadFinished(),alert("Form submission failed. Please try again. ")}}m.querySelector("#popupFormIframe").onload=
null;for(l in h){var i=document.getElementById(h[l]);i&&(i.type=="checkbox"||i.type=="radio"?e(l,i.checked):e(l,i.value))}q<3?d():setTimeout(d,200);return false}}m.style.display="";m.form.innerHTML=a.html;if(a.id)m.form.id=a.id;m.style.display="";m.style.visibility="hidden";setTimeout(function(){t("mugedaFormInitialized",{form:m.form});m.style.visibility="visible"},200);setTimeout(function(){var a=isMobile()?"touchstart":"click";b(m,"popupFormCancel").addEventListener(a,function(){g(m);self.popupFormDiv=
null},false)},500);B=m.querySelectorAll(".popupFormInput");for(o=0;o<B.length;o++)j=B[o],j.onfocus=onInputFocus,j.onblur=onInputBlur;var w;a.target?w=a.target.getBoundingClientRect():(B=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&a.isCss?(k=B.adaption,w={left:Math.max(0,(window.Mugine?1:-1)*k.marginLeft),top:window.Mugine?0:Math.max(0,(window.Mugine?1:-1)*k.marginTop),width:Math.min(k.width,B.width),height:Math.min(k.height,B.height)}):w={left:0,top:0,width:k,height:i};document.body.style.overflowY=
"auto";if(f()){if(m.style.marginLeft=Math.max(2,w.left+document.documentElement.scrollLeft+(w.width-m.offsetWidth)/2)+"px",m.style.marginTop=Math.max(2,w.top+document.documentElement.scrollTop+(w.height-m.offsetHeight)/2)+"px",m.style.marginBottom="32px",m.offsetHeight+32>document.documentElement.scrollHeight&&(m.style.marginTop=parseInt(window.getComputedStyle?getComputedStyle(m).marginTop:m.currentStyle.marginTop)+32+"px",isMobile()))document.body.style.height=m.offsetHeight+64+"px"}else if(m.style.position=
"relative",m.style.left=w.left+"px",m.style.top=w.top+"px",Math.max(2,w.top+(w.height-m.offsetHeight)/2),Math.max(2,w.left+(w.width-m.offsetWidth)/2),!c){var D=m.querySelector("form");D.style.bottom="-9999px";m.style.overflow="hidden";setTimeout(function(){m.style.background="rgba(0,0,0,0)";m.style.width=w.width+"px";m.style.height="100%";D.style.webkitTransition="none";D.style.bottom=-D.offsetHeight+"px";setTimeout(function(){D.style.webkitTransition="all 500ms";D.style.bottom="0px";D.style.overflowY=
"auto";!c&&(m.style.background="rgba(0,0,0,0.3)")},1)},1)}}}},getPopupFormHeight:function(a){for(var c=a.items,b=0,d=0,e=c.length;d<e;d++){var f=c[d];switch(f.type){case "input":case "phone":case "email":b+=44;break;case "textarea":b+=64;break;case "radio":b+=48;break;case "checkbox":f=f.value.split("\n").length;b+=32*f+8;break;case "select":b+=36;break;default:b+=44}}a.title&&(b+=60);b+=8;b+=50;b+=16;return b},processAction:function(a,c,b){var d=true;if(a.type=="pause")this.pause(a.param);else if(a.type==
"play")this.resume(1);else if(a.type=="next")this.next();else if(a.type=="previous")this.previous();else if(a.type=="nextPage")this.nextPage();else if(a.type=="prevPage")this.prevPage();else if(a.type=="disablePage")this.disablePage();else if(a.type=="enablePage")this.enablePage();else if(a.type=="gotoPage"){var e=a.param&&a.param.page_number?a.param.page_number:a.param,f=e.split(";");f.length>1&&(e=f[Math.floor(Math.random()*f.length)]);e=parseInt(e);this.gotoPage(e)}else a.type=="callback"?this.callback(a.object,
a.param):a.type=="map"?this.map(a.param):a.type=="gotoAndPlay"?(e=a.param&&a.param.frame_number?a.param.frame_number:a.param,f=typeof e=="string"?e.split(";"):[],f.length>1&&(e=f[Math.floor(Math.random()*f.length)]),e=parseInt(e),isNaN(e)&&(f=a.param&&a.param.frame_name?a.param.frame_name:"",e=Mugeda.mapFrameNameId[f],e=parseInt(e)+1),this.gotoAndPlay(e)):a.type=="gotoAndPause"||a.type=="gotoAndStop"?(e=a.param&&a.param.frame_number?a.param.frame_number:a.param,f=typeof e=="string"?e.split(";"):[],
f.length>1&&(e=f[Math.floor(Math.random()*f.length)]),e=parseInt(e),isNaN(e)&&(f=a.param&&a.param.frame_name?a.param.frame_name:"",e=Mugeda.mapFrameNameId[f],e=parseInt(e)+1),this.gotoAndPause(e)):a.type=="call"?MugedaMraid.makePhoneCall(a.param):a.type=="sms"?MugedaMraid.sendShortMessage(a.param):a.type=="email"?MugedaMraid.sendEmail(a.param):a.type=="video"?MugedaMraid.playVideo(a.param):a.type=="stopVideo"?MugedaMraid.stopVideo(a.param):a.type=="audio"?(a.param.event=c,d=false,window.Mugeda&&Mugeda.getMugedaObject&&
(f=Mugeda.getMugedaObject(),f=Math.floor(f.scene.currentId),a.unit&&a.unit.frameStart==f&&(d=true)),d=MugedaMraid.playAudio(a.param,d)):a.type=="picture"?MugedaMraid.savePicture(a.param):a.type=="calendar"?MugedaMraid.addCalendarEvent(a.param):a.type=="expand"?MugedaMraid.expand(a.param.url,0,a.param):a.type=="resize"&&MugedaMraid.expand("",1,a.param);f="actoin_type="+a.type+"&refid="+(new Date).getTime();for(item in a.param)f+="&"+item+"="+a.param[item];c=="click"&&window.event&&window.event.stopPropagation&&
window.event.stopPropagation();d&&b&&a.param.event_name&&MugedaTracker.fireEvent({category:"interaction",action:a.param.event_name,label:f,value:0})},processCloseButton:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=c,d=null;if(!b)try{window!=window.parent?(b=window.parent.document,d=window.frameElement):b=document}catch(e){b=document}if(b){var f=null;try{f=window.parent.document,f.getElementById("mugeda_expanded")||f.createElement("div")}catch(g){return}var k=a||_mrmcp.display_mode,
i=MugedaMraid.mraidReadyStatus==1?mraid.getPlacementType():"default",h=b.getElementById("mugeda_close_button");if(!h)h=b.createElement("img"),h.id="mugeda_close_button",h.style.cursor="pointer",h.style.zIndex=99999,h.style.display="block",h.style.position="fixed",h.style.right="0",h.style.top="0",h.addEventListener("click",function(){if(MugedaMraid.mraidReadyStatus!=1){b.body.removeChild(h);k=="interstitial"&&d&&d.parentNode.removeChild(d);var a=b.getElementById("mugeda_expanded");a&&b.body.removeChild(a)}}),
b.body.appendChild(h);if(i=="interstitial"||k=="auto"||k=="resize"||k=="expand"||k=="interstitial")h.src=(_mrmcp.creative_path||"")+"close_button.png",h.onerror=function(){h.style.display="none"},h.onload=function(){h.style.display=i=="interstitial"||k!="auto"?"block":"none"}}},setupMobileActionCallback:function(a){MugedaBehavior.actionCallback=a},setupMobileActions:function(a,c,b){function d(a){var b=function(a,b){var c=Math.sqrt(a.x*a.x+a.y*a.y+a.z*a.z),d=Math.sqrt(b.x*b.x+b.y*b.y+b.z*b.z);return Math.acos((a.x*
b.x+a.y*b.y+a.z*b.z)/(c*d))},d=navigator.userAgent.toLowerCase().indexOf("android")>-1,i=d?10:20,f=function(a,f,h,g){var j=Math.sqrt(a*a+f*f+h*h);if(j>=(g?20:i)){a={x:a,y:f,z:h};if(MugedaBehavior.lastMax)if(b(MugedaBehavior.lastMax,a)>Math.PI*2/3)MugedaBehavior.shakeNum++,MugedaBehavior.lastMax=a,MugedaBehavior.lastMagnitude=j;else{if(j>MugedaBehavior.lastMagnitude)MugedaBehavior.lastMax=a,MugedaBehavior.lastMagnitude=j}else MugedaBehavior.lastMax=a,MugedaBehavior.lastMagnitude=j;MugedaBehavior.shakeNum>=
(d?1:2)?(MugedaBehavior.shakeObject.dom.style.display!="none"&&(MugedaBehavior.processAction(c,c.event,true),MugedaBehavior.shakeCallback&&MugedaBehavior.shakeCallback(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(e,c.event)),y()):setTimeout(function(){y()},3E3)}},h=0,g=0,j=0;if(a.acceleration===null||a.acceleration.x===void 0||a.acceleration.y===void 0||a.acceleration.z===void 0||a.acceleration.x===null||a.acceleration.y===null||a.acceleration.z===null){if(a.accelerationIncludingGravity)h=
a.accelerationIncludingGravity.x,g=a.accelerationIncludingGravity.y,j=a.accelerationIncludingGravity.z,f(h,g,j,1)}else h=a.acceleration.x,g=a.acceleration.y,j=a.acceleration.z,f(h,g,j,0)}var e=a.dataRef||a.aniData,f=a.dom?a.dom:window,g=isMobile()?"touchstart":"mousedown",k=isMobile()?"touchend":"mouseup",i=isMobile()?"touchmove":"mousemove",h=null,t=0,v=0,j=0,o=0,r=0,q=0,n=function(a){var b=o-t,c=r-v,d=null;if(q-j<2E3&&(Math.abs(b)>32||Math.abs(c)>32))b=Math.atan2(-c,b)*180/Math.PI,-22.5<b&&b<=22.5?
d="slide_right":22.5<b&&b<=67.5?d="slide_right_up":67.5<b&&b<=112.5?d="slide_up":112.5<b&&b<=157.5?d="slide_left_up":157.5<b||b<=-157.5?d="slide_left":-157.5<b&&b<=-112.5?d="slide_left_down":-112.5<b&&b<=-67.5?d="slide_down":-67.5<b&&b<=-22.5&&(d="slide_right_down");b=a.slideHash?a.slideHash[d]||{}:{};a=b.behavior||{};b=b.callback;d&&a.event==d&&(MugedaBehavior.processAction(a,a.event,true),b&&b(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(e,a.event));h=null;return d};if(c.event==
"touch_start")a.touchstartBehavior=c,a.touchStartCallback=b;a.slideHooked||f.addEventListener(g,function(b){b.preventDefault();h=a;var c=b.targetTouches?b.targetTouches[0]:null;t=c?c.pageX:b.pageX;v=c?c.pageY:b.pageY;j=(new Date).getTime();a.touchstartBehavior&&a.touchstartBehavior.event=="touch_start"&&a.dom.style.display!="none"&&(MugedaBehavior.processAction(a.touchstartBehavior,a.touchstartBehavior.event,true),a.touchStartCallback&&a.touchStartCallback(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(e,
a.touchstartBehavior.event))});if(c.event=="touch_end")a.touchendBehavior=c,a.touchendCallback=b;if(c.event.indexOf("slide_")==0)f.slideHash=f.slideHash||{},f.slideHash[c.event]={behavior:c,callback:b};a.slideHooked||f.addEventListener(k,function(b){b.preventDefault();h=null;var c=b.changedTouches?b.changedTouches[0]:null;o=c?c.pageX:b.pageX;r=c?c.pageY:b.pageY;q=(new Date).getTime();n(f)&&b.stopPropagation();a.touchendBehavior&&a.touchendBehavior.event=="touch_end"&&a.dom.style.display!="none"&&
(MugedaBehavior.processAction(a.touchendBehavior,a.touchendBehavior.event,true),a.touchendCallback&&a.touchendCallback(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(e,a.touchendBehavior.event))});!a.slideHooked&&f.addEventListener(i,function(){});!a.slideHooked&&!isMobile()&&window.addEventListener(k,function(a){if(h)o=a.pageX,r=a.pageY,q=(new Date).getTime(),a.preventDefault(),n(f)&&a.stopPropagation()});a.slideHooked=true;var y=function(){MugedaBehavior.shakeNum=0;MugedaBehavior.lastMax=
null};if(c.event=="shake"&&window.DeviceMotionEvent&&(y(),!a.shakeHooked))MugedaBehavior.shakeObject=a,MugedaBehavior.shakeCallback=b,window.addEventListener("devicemotion",d,false),a.shakeHooked=true}};
MugedaTracker={fireEvent:function(a){if(!window.location||!window.location.host){var a=(_mrmcp.track_bot||"http://cdn.mugeda.com/media/pages/track/track_20131030.html")+"?"+(_mrmma_var1||"var1=none")+"&"+(_mrmma_var2||"var2=none")+"&category="+a.category+"&action="+a.action+"&label="+encodeURIComponent(a.label)+"&value="+a.value+"&noninteraction="+a.noninteraction,c=document.createElement("iframe");c.id=_mrmcp.creative_id;c.src=a;c.style.display="none";c.style.width="1px";c.style.height="1px";document.body.appendChild(c)}else if(this.fireGAEvent(a.category,
a.action,a.label,a.value,a.noninteraction),this.fireMUEvent(a.category,a.action,a.label,a.value),window.mugedaGetCustomTracker&&(c=window.mugedaGetCustomTracker())){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=_mrmcp.custom_params,d=_mrmma_tags;b&&b.indexOf("%CUSTOMPARAM%")<0&&(d+="&"+b);c(d,a.category,a.action,a.label,a.value)}},fireGAEvent:function(a,c,b,d,e){typeof _gaq!="undefined"&&(_gaq.push(["_trackEvent",a,c,b,d,e]),typeof _ga_mugeda_use_custom!="undefined"&&_gaq.push(["custom._trackEvent",
a,c,b,d,e]))},fireMUEvent:function(a,c,b,d){typeof _mugeda_tracker!="undefined"&&_mugeda_tracker.trackEvent({action:c,category:a,label:b,value:d})}};
function mraidReady(){parseFloat(mraid.getVersion())-0.999>0?(MugedaMraid.mraidReadyStatus=1,_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp,_mrmcp.display_mode&&(mraid.useCustomClose(true),MugedaBehavior.processCloseButton()),mraid.addEventListener("error",function(){}),mraid.addEventListener("stateChange",function(){var a=mraid.getState();MugedaMraid.setMraidState(a)}),mraid.addEventListener("sizeChange",function(){})):console.log("mraidReady is called, but with no correct version (>= 1.0) supported.")}
var mraidReadyTimeout,mraidTimeOut=100,mraidCounter=0;function readyListener(){typeof mraid==="undefined"?(mraidCounter++,mraidCounter<mraidTimeOut&&(mraidReadyTimeout=setTimeout(readyListener,100))):mraid.getState()==="loading"?mraid.addEventListener("ready",mraidReady):mraidReady()}readyListener();
try{var htmlDoc=document.getElementsByTagName("head").item(0),js=document.createElement("script"),s="mraid.js";js.setAttribute("type","text/javascript");js.setAttribute("src",s);htmlDoc.appendChild(js);js.onload=function(){};js.onerror=function(){}}catch(e$$21){alert(e$$21.toString())}Mugeda=window.Mugeda||{};
Mugeda.Analytics=function(a,c){var b=[],d=0,a=a||"http://cn-stat.mugeda.com/stats/c.gif",c=c||a;this.setAccount=function(){};this.setCustomVar=function(a,c,d){a=a||0;b[a]&&delete b[a];b[a]={};b[a][c]=d||""};var e=function(a){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(a+"="),c_start!=-1)){c_start=c_start+a.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end))}return""},f=function(){e("clientId");
for(var a=[],c=0;c<b.length;c++)for(var d in b[c])a[c]=d+"="+encodeURIComponent(b[c][d]);return a.join("&")},g=function(a){for(var b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),c=Number(+new Date).toString(36),d=0,e="",f=b.length;d<a;d++)e+=b[Math.floor(Math.random()*f)];return c+e.toLowerCase()},k=function(){var a=location.pathname,b=/(?:\/animation\/edit)|(?:\/page\/edit)|(?:\/default\/preview\.html)|(?:\/client\/preview(?:_css3)?\.html)/;return!location.host||b.test(a)?
false:true};this.trackPageview=function(b){if(k()){this.startTime=(new Date).getTime();var c=a,t=new Image,v=c.indexOf("?")!=-1?"&":"?",j=_mrmcp.width||window._mrmma_width,o=_mrmcp.height||window._mrmma_height,r=_mrmcp.title||window._mrmma_title,q=window._mrmma_var1?_mrmma_var1.substring(_mrmma_var1.indexOf("time")+5):+new Date,n=window.location.host,j=j+"x"+o,o=window.location.href.slice(window.location.href.indexOf("/",8)),y=screen.width+"x"+screen.height,b=b||{};b.msv="0.1.0";b.msa="MU-A001";b.msh=
n;b.mscs=j;b.msp=o;b.mssr=y;b.mssi=g(16);b.mscn=r;b.msct=q;b.crid=_mrmcp.creative_id||"";for(var z in b)b.hasOwnProperty(z)&&(this.setCustomVar(d,z,b[z]),d++);b=e("msuid");if(!b)r=b=g(32),q=new Date,q.setDate(q.getDate()+3650),document.cookie="msuid="+escape(r)+(3650==null?"":";expires="+q.toGMTString())+"; domain=.mugeda.com; path=/";this.setCustomVar(d++,"msuid",b);b=f();t.src=c+v+("mst=1&"+b)}};this.trackEvent=function(a){if(k()){var b=new Image,d=c,e=d.indexOf("?")!=-1?"&":"?",g=f(),a=a||{},o=
(new Date).getTime(),r=o-this.startTime,q=encodeURIComponent(a.action||"submit"),n=encodeURIComponent(a.categroy||"weika"),y=encodeURIComponent(a.label||""),a=parseInt(a.value)||0;b.src=d+e+g+"&mst=2&msts="+o+"&msetd="+r+"&msen="+q+"&msev="+a+"&msec="+n+"&msel="+y}}};try{window._mugeda_tracker=new Mugeda.Analytics,_mugeda_tracker.trackPageview()}catch(e$$22){}
function createFontFaceStyle(a,c){var b=document.getElementById("cloudfont-"+c);if(!b){a.toLowerCase()=="simhei"&&(a='"Microsoft YaHei", "\u5fae\u8f6f\u96c5\u9ed1", SimHei, sans-serif');var b=document.createElement("style"),d=document.createTextNode('@font-face {font-family:"'+a+'";src:url('+c+') format("truetype");}');b.id="cloudfont-"+c;b.type="text/css";b.appendChild(d);document.head.appendChild(b)}};
